# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16.3

# Mod Properties
mod_version=1.0.0
maven_group=me.ngcsonsplash.mcwebsocket

# Dependencies
fabric_api_version=0.151.0+26.1.2

# Low RAM optimization for Gradle
org.gradle.jvmargs=-Xmx512m
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=true